//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bumblebee.RegistrationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationServiceReference.RegistrationWebServiceSoap")]
    public interface RegistrationWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCustomer", ReplyAction="*")]
        Bumblebee.RegistrationServiceReference.insertCustomerResponse insertCustomer(Bumblebee.RegistrationServiceReference.insertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Bumblebee.RegistrationServiceReference.insertCustomerResponse> insertCustomerAsync(Bumblebee.RegistrationServiceReference.insertCustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCustomer", Namespace="http://tempuri.org/", Order=0)]
        public Bumblebee.RegistrationServiceReference.insertCustomerRequestBody Body;
        
        public insertCustomerRequest() {
        }
        
        public insertCustomerRequest(Bumblebee.RegistrationServiceReference.insertCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ConfirmPassword;
        
        public insertCustomerRequestBody() {
        }
        
        public insertCustomerRequestBody(string Name, string Email, string Address, string Password, string ConfirmPassword) {
            this.Name = Name;
            this.Email = Email;
            this.Address = Address;
            this.Password = Password;
            this.ConfirmPassword = ConfirmPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bumblebee.RegistrationServiceReference.insertCustomerResponseBody Body;
        
        public insertCustomerResponse() {
        }
        
        public insertCustomerResponse(Bumblebee.RegistrationServiceReference.insertCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertCustomerResult;
        
        public insertCustomerResponseBody() {
        }
        
        public insertCustomerResponseBody(string insertCustomerResult) {
            this.insertCustomerResult = insertCustomerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrationWebServiceSoapChannel : Bumblebee.RegistrationServiceReference.RegistrationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationWebServiceSoapClient : System.ServiceModel.ClientBase<Bumblebee.RegistrationServiceReference.RegistrationWebServiceSoap>, Bumblebee.RegistrationServiceReference.RegistrationWebServiceSoap {
        
        public RegistrationWebServiceSoapClient() {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bumblebee.RegistrationServiceReference.insertCustomerResponse Bumblebee.RegistrationServiceReference.RegistrationWebServiceSoap.insertCustomer(Bumblebee.RegistrationServiceReference.insertCustomerRequest request) {
            return base.Channel.insertCustomer(request);
        }
        
        public string insertCustomer(string Name, string Email, string Address, string Password, string ConfirmPassword) {
            Bumblebee.RegistrationServiceReference.insertCustomerRequest inValue = new Bumblebee.RegistrationServiceReference.insertCustomerRequest();
            inValue.Body = new Bumblebee.RegistrationServiceReference.insertCustomerRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Email = Email;
            inValue.Body.Address = Address;
            inValue.Body.Password = Password;
            inValue.Body.ConfirmPassword = ConfirmPassword;
            Bumblebee.RegistrationServiceReference.insertCustomerResponse retVal = ((Bumblebee.RegistrationServiceReference.RegistrationWebServiceSoap)(this)).insertCustomer(inValue);
            return retVal.Body.insertCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bumblebee.RegistrationServiceReference.insertCustomerResponse> Bumblebee.RegistrationServiceReference.RegistrationWebServiceSoap.insertCustomerAsync(Bumblebee.RegistrationServiceReference.insertCustomerRequest request) {
            return base.Channel.insertCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bumblebee.RegistrationServiceReference.insertCustomerResponse> insertCustomerAsync(string Name, string Email, string Address, string Password, string ConfirmPassword) {
            Bumblebee.RegistrationServiceReference.insertCustomerRequest inValue = new Bumblebee.RegistrationServiceReference.insertCustomerRequest();
            inValue.Body = new Bumblebee.RegistrationServiceReference.insertCustomerRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Email = Email;
            inValue.Body.Address = Address;
            inValue.Body.Password = Password;
            inValue.Body.ConfirmPassword = ConfirmPassword;
            return ((Bumblebee.RegistrationServiceReference.RegistrationWebServiceSoap)(this)).insertCustomerAsync(inValue);
        }
    }
}
