//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bumblebee.AdminServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceReference.AdminPanelWebServiceSoap")]
    public interface AdminPanelWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ProductID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertProduct", ReplyAction="*")]
        Bumblebee.AdminServiceReference.insertProductResponse insertProduct(Bumblebee.AdminServiceReference.insertProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<Bumblebee.AdminServiceReference.insertProductResponse> insertProductAsync(Bumblebee.AdminServiceReference.insertProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertProduct", Namespace="http://tempuri.org/", Order=0)]
        public Bumblebee.AdminServiceReference.insertProductRequestBody Body;
        
        public insertProductRequest() {
        }
        
        public insertProductRequest(Bumblebee.AdminServiceReference.insertProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProductID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Productname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProductPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string categoryname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Brandname;
        
        public insertProductRequestBody() {
        }
        
        public insertProductRequestBody(string ProductID, string Productname, string ProductPrice, string categoryname, string Brandname) {
            this.ProductID = ProductID;
            this.Productname = Productname;
            this.ProductPrice = ProductPrice;
            this.categoryname = categoryname;
            this.Brandname = Brandname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bumblebee.AdminServiceReference.insertProductResponseBody Body;
        
        public insertProductResponse() {
        }
        
        public insertProductResponse(Bumblebee.AdminServiceReference.insertProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertProductResult;
        
        public insertProductResponseBody() {
        }
        
        public insertProductResponseBody(string insertProductResult) {
            this.insertProductResult = insertProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminPanelWebServiceSoapChannel : Bumblebee.AdminServiceReference.AdminPanelWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminPanelWebServiceSoapClient : System.ServiceModel.ClientBase<Bumblebee.AdminServiceReference.AdminPanelWebServiceSoap>, Bumblebee.AdminServiceReference.AdminPanelWebServiceSoap {
        
        public AdminPanelWebServiceSoapClient() {
        }
        
        public AdminPanelWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminPanelWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminPanelWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminPanelWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bumblebee.AdminServiceReference.insertProductResponse Bumblebee.AdminServiceReference.AdminPanelWebServiceSoap.insertProduct(Bumblebee.AdminServiceReference.insertProductRequest request) {
            return base.Channel.insertProduct(request);
        }
        
        public string insertProduct(string ProductID, string Productname, string ProductPrice, string categoryname, string Brandname) {
            Bumblebee.AdminServiceReference.insertProductRequest inValue = new Bumblebee.AdminServiceReference.insertProductRequest();
            inValue.Body = new Bumblebee.AdminServiceReference.insertProductRequestBody();
            inValue.Body.ProductID = ProductID;
            inValue.Body.Productname = Productname;
            inValue.Body.ProductPrice = ProductPrice;
            inValue.Body.categoryname = categoryname;
            inValue.Body.Brandname = Brandname;
            Bumblebee.AdminServiceReference.insertProductResponse retVal = ((Bumblebee.AdminServiceReference.AdminPanelWebServiceSoap)(this)).insertProduct(inValue);
            return retVal.Body.insertProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bumblebee.AdminServiceReference.insertProductResponse> Bumblebee.AdminServiceReference.AdminPanelWebServiceSoap.insertProductAsync(Bumblebee.AdminServiceReference.insertProductRequest request) {
            return base.Channel.insertProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bumblebee.AdminServiceReference.insertProductResponse> insertProductAsync(string ProductID, string Productname, string ProductPrice, string categoryname, string Brandname) {
            Bumblebee.AdminServiceReference.insertProductRequest inValue = new Bumblebee.AdminServiceReference.insertProductRequest();
            inValue.Body = new Bumblebee.AdminServiceReference.insertProductRequestBody();
            inValue.Body.ProductID = ProductID;
            inValue.Body.Productname = Productname;
            inValue.Body.ProductPrice = ProductPrice;
            inValue.Body.categoryname = categoryname;
            inValue.Body.Brandname = Brandname;
            return ((Bumblebee.AdminServiceReference.AdminPanelWebServiceSoap)(this)).insertProductAsync(inValue);
        }
    }
}
